### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pocopocox3** [YashPS/StockChecker#4]
Traceback (most recent call last):
  File "C:\Users\ACER\Desktop\StockChecker-master\checker.py", line 63, in <module>
    check_inventory()
  File "C:\Users\ACER\Desktop\StockChecker-master\checker.py", line 53, in check_inventory
    element_name = conf['element_name']
KeyError: 'element_name'

**Comment by YashPS** [comment]
Well spotted, this is an outdated build, will update it from my local soon.
